version: '3'

networks:
  directus:

volumes:
  jp_node_modules:

services:
  directus:
    image: directus/directus:10.7.2
    ports:
      - 8065:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./directus/extensions:/directus/extensions
    # entrypoint: docker-entrypoint.sh  
    networks:
      - directus
    env_file:
      - .env.dev
  juspoliticum-ui:
    build: juspoliticum-ui
    image: juspoliticum-ui
    restart: "no"
    volumes:
      - ./juspoliticum-ui/:/app
      - ./juspoliticum-ui/node_modules:/app/node_modules
    ports:
      - "4321:4321"
    depends_on:
      - directus
 

