version: '3'

volumes:
  jp_node_modules:

services:
  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./directus/extensions:/directus/extensions
    # entrypoint: docker-entrypoint.sh  
    env_file:
      - ./directus/.env.dev
    working_dir: /directus
  droitphilosophie-ui:
    build: droitphilosophie-ui
    image: droitphilosophie-ui
    restart: "no"
    volumes:
      - ./droitphilosophie-ui/:/app
      - ./droitphilosophie-ui/node_modules:/app/node_modules
    ports:
      - "4321:4321"
    depends_on:
      - directus
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 256M
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

