version: '3'

networks:
  directus:

services:
  directus:
    image: directus/directus:10.7.1
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./directus/extensions:/directus/extensions
    # entrypoint: docker-entrypoint.sh  
    networks:
      - directus
    env_file:
      - .env.dev
