volumes:
  jp_node_modules:
  data:

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dev-mariadb/directus_villey_2023-11-24_06-44-01.sql:/docker-entrypoint-initdb.d/directus_villey_2023-11-24_06-44-01.sql
      - ./dev-mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - directus-net

  directus:
    image: directus/directus:10.10.7
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file:
      - ./directus/.env.dev
    working_dir: /directus
    depends_on:
      - db
    networks:
      - directus-net

  droitphilosophie-ui:
    build: droitphilosophie-ui
    image: droitphilosophie-ui
    restart: "no"
    volumes:
      - ./droitphilosophie-ui/:/app
      - ./droitphilosophie-ui/node_modules:/app/node_modules
    ports:
      - "4321:4321"
    depends_on:
      - directus
    networks:
      - directus-net
  juspoliticum-ui:
    build: juspoliticum-ui
    image: juspoliticum-ui
    restart: "no"
    volumes:
      - ./juspoliticum-ui/:/app
      - ./juspoliticum-ui/node_modules:/app/node_modules
    ports:
      - "4322:4322"
    depends_on:
      - directus
    networks:
      - directus-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 256M
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - directus-net

networks:
  directus-net:
    driver: bridge
